/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jni_update_patch_server_BsDiff */

#ifndef com_example_myandroidproject_ndk_patch_update_Main
#define com_example_myandroidproject_ndk_patch_update_Main
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_myandroidproject_ndk_patch_update_Main_dispatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
